-- Adicionar coluna ID_PAGAMENTO na tabela COMPRA
ALTER TABLE `COMPRA`
ADD COLUMN `ID_PAGAMENTO` varchar(255) DEFAULT NULL AFTER `VALOR`;

-- Atualizar a estrutura da tabela COMPRA para incluir AUTO_INCREMENT
ALTER TABLE `COMPRA`
MODIFY `ID_COMPRA` int NOT NULL AUTO_INCREMENT; 