-- --------------------------------------------------------

--
-- Estrutura para tabela `CARRINHO`
--

CREATE TABLE `CARRINHO` (
  `ID_CARRINHO` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `ID_CURSO` int NOT NULL,
  `DATA_ADICAO` datetime NOT NULL,
  PRIMARY KEY (`ID_CARRINHO`),
  UNIQUE KEY `unique_carrinho_item` (`ID_USUARIO`,`ID_CURSO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  KEY `ID_CURSO` (`ID_CURSO`),
  CONSTRAINT `CARRINHO_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE CASCADE,
  CONSTRAINT `CARRINHO_ibfk_2` FOREIGN KEY (`ID_CURSO`) REFERENCES `CURSOS` (`ID_CURSO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 