CREATE TABLE `COMPRA` (
  `ID_COMPRA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `FORMA_PAGAMENTO` varchar(50) NOT NULL,
  `DATA_COMPRA` datetime NOT NULL,
  `STATUS` tinyint NOT NULL DEFAULT '1',
  `VALOR` decimal(10,2) NOT NULL,
  `ID_PAGAMENTO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_COMPRA`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `COMPRA_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 